#!/bin/bash

curdir="`dirname $(readlink -f $0)`"
source $curdir/../../lib/common.sh

grep -q "source $curdir/.bashrc_ad" ~/.bashrc || echo "source $curdir/.bashrc_ad" >> ~/.bashrc

cecho g "bashrc install succeeded"
cecho r 'need to run "source ~/.bashrc"'
