#!/bin/bash

curdir="`dirname $(readlink -f $0)`"
source $curdir/../../lib/common.sh

rm -f ~/.gdbinit
rm -rf ~/.gdbinit.d

cp $curdir/.gdbinit ~/.gdbinit
cp -r $curdir/.gdbinit.d  ~/.gdbinit.d

pkg_install() {
    if command -v yum &>/dev/null; then
        sudo yum install -y python-pygments
    elif command -v apt-get &>/dev/null; then
        sudo apt-get install -y python-pygments
    fi
}

cecho -G "gdb pro ready!"
