#!/bin/bash

curdir="`dirname $(readlink -f $0)`"
source $curdir/../../lib/common.sh

rm -f ~/.gdbinit
rm -rf ~/.gdbinit.d

cp $curdir/.gdbinit ~/.gdbinit
cp -r $curdir/.gdbinit.d  ~/.gdbinit.d

type yum && yum install -y python-pygments

cecho -G "gdb pro ready!"
