#!/bin/bash
#
# Awesome Devops (or maybe another AirDrop)
#
# TODO
# 1. 支持mac命令行工具
# 2. 支持bash completion

_curdir="`dirname $(readlink -f $0)`"
source $_curdir/lib/common.sh

_puturl="http://10.151.170.16:8889"
_geturl="http://10.151.170.16:8890"

put()
{
    _name=`basename $1`
    _r_file=${2:-$_name}
    curl -T $1 $_puturl/$_r_file > /dev/null
    if [[ $? -eq 0 ]]; then
        md5sum $1
        cecho g "$_geturl/$_r_file"
    fi
}

get()
{
    _name=`basename $1`
    _l_file=${2:-$_name}
    curl -o $_l_file $_geturl/$_name
    md5sum $_l_file
    cecho g "`readlink -f $_l_file`"
}

upgrade()
{
    sh $_curdir/install.sh
}

usage(){

    cat <<__EOF__

⚙ Awesome Devops (or maybe another AirDrop) ⚙

Install:
bash <(curl -s $_geturl/@aadi@) && source ~/.bashrc

Usage:  ad [ PLUGIN | COMMAND ] [help]

    PLUGIN deploy:
__EOF__
    for i in `ls $_curdir/plugins/`; do
        echo "        ${i##*/}"
    done

cat <<__EOF__

    COMMANDS:
        help
        put
        get
        upgrade
__EOF__
    for i in `ls $_curdir/tools/`; do
        echo "        ${i##*/}"
    done

    [ "$_action" == "help" ] && exit 0 || exit 1
}

_action=$1; shift;

if [[ -z $_action ]]; then
    usage
    exit 1
fi

if [[ -d $_curdir/plugins/$_action ]]; then
    $_curdir/plugins/$_action/install
else
    case $_action in
        put)
            put "$@"
            ;;
        get)
            get "$@"
            ;;
        help)
            usage
            ;;
        upgrade)
            upgrade
            ;;
        *)
            if [[ -f $_curdir/tools/$_action ]]; then
                $_curdir/tools/$_action "$@"
            elif [[ -d $_curdir/tools/$_action ]]; then
                $_curdir/tools/$_action/$_action "$@"
            else
                usage
                exit 1
            fi
            ;;
    esac
fi
