#!/bin/bash

curdir="`dirname $(readlink -f $0)`"
source $curdir/../../lib/common.sh

if ! grep -q "source $curdir/.git-completion.bash" ~/.bashrc; then
    echo -e "\nsource $curdir/.git-completion.bash" >> ~/.bashrc
fi

cecho g "git plus ready!"
cecho r 'need to run "source ~/.bashrc"'
