#!/bin/bash

curdir="`dirname $(readlink -f $0)`"
source $curdir/../../lib/common.sh

if ! grep -q "source $curdir/.git-completion.bash" ~/.bashrc; then
    echo -e "\nsource $curdir/.git-completion.bash #@ad_plugins@" >> ~/.bashrc
fi

cecho -G "git plus ready!"
cecho -R 'need to run "source ~/.bashrc"'
