#!/bin/bash

curdir="`dirname $(readlink -f $0)`"
source $curdir/../../lib/common.sh

cd ~/bin
ad get @bpftrace@ bpftrace
chmod +x bpftrace

cecho -G "bpftrace install succeeded"
cecho -R 'need to run "source ~/.bashrc"'
