#!/bin/bash -e
# Copyright © 2021 Ouyang Xiongyi. All Rights Reserved.

_curdir="`dirname $(readlink -f $0)`"
source $_curdir/../../lib/common.sh
FG_PATH=$_curdir/FlameGraph

if [[ $# -lt 2 ]]; then
    echo "Wrong args!!!"
    echo "Example1: cpi_ff \"-p <PID>\" svg_file_name"
    echo "Example2: cpi_ff \"-t <TID>\" svg_file_name"
    echo "Example2: cpi_ff \"-C <CORE_IDX>\" svg_file_name"
    exit 1
fi

mkdir -p /tmp

# intel
if perf list | grep cycle_activity.stalls_total > /dev/null 2>&1; then
    STALL_PMU=cycle_activity.stalls_total
elif perf list | grep ic_fetch_stall.ic_stall_any > /dev/null 2>&1; then
    STALL_PMU=ic_fetch_stall.ic_stall_any
else
    CPU_VENDOR=unknown_vendor
fi

cpi_ff()
{
    # cpu PMU查询（XEON系列要注意找“Server Events”的表） https://perfmon-events.intel.com/#
    perf record $1 -e cpu-cycles,$STALL_PMU -c 2000003 --call-graph dwarf -F 200 -- sleep 5

    # !!! perf script一定要按照stackcollapse-perf.pl的使用说明去掉无关的域，否则无法上色，不同的perf/kernel版本用法有出入，自行解决
    #
    # $./FlameGraph/stackcollapse-perf.pl -h
    # ...
    # [1] perf script must emit both PID and TIDs for these to work; eg, Linux < 4.1:
    #         perf script -f comm,pid,tid,cpu,time,event,ip,sym,dso,trace
    #     for Linux >= 4.1:
    #         perf script -F comm,pid,tid,cpu,time,event,ip,sym,dso,trace
    #     If you save this output add --header on Linux >= 3.14 to include perf info.
    perf script -F comm,pid,tid,time,event,ip,sym,dso > /tmp/out.perf

    $FG_PATH/stackcollapse-perf.pl --event-filter=cpu-cycles /tmp/out.perf > /tmp/out.folded.cycles
    $FG_PATH/stackcollapse-perf.pl --event-filter=$STALL_PMU /tmp/out.perf > /tmp/out.folded.stalls
    $FG_PATH/difffolded.pl -n /tmp/out.folded.stalls /tmp/out.folded.cycles | $FG_PATH/flamegraph.pl --title "CPI Flame Graph: blue=stalls, red=instructions" --width=1200 > $2.svg
}

other_ff()
{
    perf record $1 --call-graph dwarf -F 200 -- sleep 5

    perf script | $FG_PATH/stackcollapse-perf.pl > /tmp/out.perf
    cat /tmp/out.perf | $FG_PATH/flamegraph.pl --width=1200 > $2.svg
}

set -x

case $CPU_VENDOR in
    "unknown_vendor")
        other_ff "$@"
        ;;
    *)
        cpi_ff "$@"
        ;;
esac

set +x

cecho -G "Finish. Output file: $2.svg"
