#!/bin/bash

if [ -z $1 ]; then
    echo "Usage: $0 <CPU_LIST e.g. 0,3,7-11>"
    exit 1
fi

pkg_install() {
    if command -v yum &>/dev/null; then
        sudo yum install -y stress
    elif command -v apt-get &>/dev/null; then
        sudo apt-get install -y stress
    fi
}

if ! type stress >/dev/null 2>&1; then
    pkg_install || {
        ad cecho -R "ERROR: Install \"stress\" failed"
        exit 1
    }
fi

taskset -c $1 stress -c $(nproc --all)
