#!/bin/bash

_curdir="`dirname $(readlink -f $0)`"
source $_curdir/../lib/common.sh

if [[ $# != 2 ]]; then
    cecho -R "Wrong args!!!"
    echo 'Usage: login_free <host file> <unified password>'
    exit 1
fi

hostfile=$1
passwd=$2
if [[ ! -f $hostfile ]]; then
    cecho -R "$hostfile is not a regular file!"
    exit 1
fi

type expect >/dev/null 2>&1 || sudo yum install -y expect
if ! type expect >/dev/null 2>&1; then
    cecho -R "expect tool is not found!"
    exit 1
fi

if [[ ! -f ~/.ssh/id_rsa.pub ]]; then
    ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
fi
id_rsa_pub=`cat ~/.ssh/id_rsa.pub`

for _nc in `cat $hostfile | awk '!/^#/'`; do
    cecho -G "\n[$_nc] ..."
expect <<EOF
    set timeout 5
    spawn ssh $_nc "mkdir -p ~/.ssh; echo $id_rsa_pub >> ~/.ssh/authorized_keys"
    expect {
        "*(yes/no)*" { send "yes\r"; exp_continue }
        "*password:" { send "$passwd\r" }
    }
    expect eof
EOF
done
